spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?userUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true  # 打印sql语句

logging:
  level: 
    root: warn
    '[com.adi]': info    
  file:
    path: log/blog-pro.log
server:
  port: 8081
